@startuml

actor User
User -> StartupActivity: <<open app>>
activate StartupActivity
StartupActivity -> MainActivity: onStart()
activate MainActivity
activate StopCondition
activate PeakFinder
deactivate StartupActivity

MainActivity -> RecorderTask: <<create>>
activate RecorderTask
MainActivity -> RecorderTask: execute()
RecorderTask -> RecorderTask: onPeriodicNotification()
activate RecorderTask

RecorderTask -> ProcessorTask: <<create>>
activate ProcessorTask
RecorderTask -> ProcessorTask: execute()
ProcessorTask -> PeakFinder: getPops()
PeakFinder --> ProcessorTask: Updated Pops

ProcessorTask -> StopCondition: conditionSatisfied()
StopCondition --> ProcessorTask: <font color=red><b>Not satisfied


ProcessorTask -> RecorderTask: onProgressUpdate()
destroy ProcessorTask
deactivate RecorderTask
...
== Repetition ==
...
RecorderTask -> RecorderTask: onPeriodicNotification()
activate RecorderTask

RecorderTask -> ProcessorTask: <<create>>
activate ProcessorTask
RecorderTask -> ProcessorTask: execute()
ProcessorTask -> PeakFinder: getPops()
PeakFinder --> ProcessorTask: Updated Pops

ProcessorTask -> StopCondition: conditionSatisfied()
StopCondition --> ProcessorTask: <font color=blue><b>Satisfied


ProcessorTask -> RecorderTask: onProgressUpdate()
destroy ProcessorTask
deactivate RecorderTask

RecorderTask -> MainActivity: onProgressUpdate()

== User Confirmation ==

MainActivity -> MainActivity: stopAll()

destroy StopCondition
destroy PeakFinder
destroy MainActivity

activate StartupActivity
MainActivity -> StartupActivity
@enduml